### ISSUE TITLE
[BUG] - Outer Shadow applies color correction

### ISSUE THREAD

**Issue by iammesutkaya** [FiniteSingularity/obs-stroke-glow-shadow#20]
**Describe the bug**
Applying an outer shadows, seems to apply some sort of color correction

**To Reproduce**
1. Apply Shadow filter
2. Choose Outer Shadow

**Expected behavior**
There shouldn't be any color correction

**Screenshots**
![CleanShot 2023-10-05 at 12 13 14@2x](https://github.com/FiniteSingularity/obs-stroke-glow-shadow/assets/6351305/612f0ece-0cfe-4170-92f5-2bf1a15ca2de)
![CleanShot 2023-10-05 at 12 13 26@2x](https://github.com/FiniteSingularity/obs-stroke-glow-shadow/assets/6351305/4c392ef7-36aa-45ae-adbb-bf0c6b0fd030)

**Environment**
 - OS/Version: Mac OS 14
 - OBS Version: 29.1.3
 - Composite Blur Plugin Version: 1.0
 - Blur Algorithm/Type: Triangular & Dual Kawase

**GPU**
 - GPU make/model Mac Mini M1

**Additional context**
Didn't have the bug with the previous version

**Comment by FiniteSingularity** [comment]
Thank you for opening the issue @iammesutkaya.  May I ask what type of source you're applying the filter to, so that I can replicate the issue?  It looks like it might be a camera source embedded in a scene or group?

**Comment by iammesutkaya** [comment]
Yes, I initially noticed it on a camera source, but then tested it again on a color source. Same behaviour.

![CleanShot 2023-10-05 at 14 33 56@2x](https://github.com/FiniteSingularity/obs-stroke-glow-shadow/assets/6351305/55536de3-02cb-43c4-8ecb-c2e710ace839)
![CleanShot 2023-10-05 at 14 34 01@2x](https://github.com/FiniteSingularity/obs-stroke-glow-shadow/assets/6351305/1673d45e-5712-474f-8bab-9250ea3d7085)

**Comment by FiniteSingularity** [comment]
Thank you for this.  I'll take a look at it this morning and try to figure out what is going on (it likely has to do with the conversion from sRGB color space to linear color space and back, which is necessary for proper mixing).

In the short term- a workaround would be to use the effect source (rather than the filter) and layer the shadow behind your webcam source.  The effect source only uses your source as a mask, but doesn't attempt to mix any colors (and leaves the compositing/color mixing up to OBS).  Something you might want to try as I work to fix this issue.

**Comment by iammesutkaya** [comment]
Yeah, that should work, thanks! Glad I could help!

**Comment by FiniteSingularity** [comment]
I have confirmed the bug on Windows as well in the latest version of the code.  Looking into it this morning.

**Comment by FiniteSingularity** [comment]
Hi @iammesutkaya -

I found what was causing the issue and fixed it.  I've merged in the changes, and will be generating a 1.0.1 release shortly.  Please give the 1.0.1 release a try, and verify that it fixes the issue for you.

**Comment by FiniteSingularity** [comment]
Ok, v1.0.1 with the fix is available at https://github.com/FiniteSingularity/obs-stroke-glow-shadow/releases/tag/v1.0.1

**Comment by iammesutkaya** [comment]
Yes, it's fixed! Thank you!
