### ISSUE TITLE
[BUG] - Glow & Stroke effects are cropped within the "bounding box" of a TextType2 source

### ISSUE THREAD

**Issue by LividJava** [FiniteSingularity/obs-stroke-glow-shadow#43]
**Describe the bug**
When using Glow or Stroke filter effects, the bounding box of the TextType2 source cuts off the effect. TextType2 is only available on Linux as far as I'm aware.

**To Reproduce**
1. On a Linux machine, create a Text source using TextType2.
2. Apply either a Stroke or Glow effect filter.

**Expected behavior**
The bounding box of the source should grow with the applied effects.

**Screenshots**
![strokebug](https://github.com/user-attachments/assets/b7cb9714-c242-47b9-8c8c-4f1b423fbbaa)
![glowbug](https://github.com/user-attachments/assets/1a448d89-a3ee-4b68-8447-428dff25c1dc)

**Environment**
 - OS/Version: Arch Linux 6.10.0-arch1-2
 - OBS Version: 30.2.2-tytan652-1
 - Stroke Glow Shadow: 1.0.2

**GPU**
 - GPU make/model AMD RX 480
 - GPU VRAM 8GB

**Additional context**
I am not sure if the appropriate term is Bounding Box or Render Area. So that could be a misused term.

**Comment by FiniteSingularity** [comment]
Hi @LividJava-

That is a current limitation of the plugin. I am working on a new release that will include an option to automatically extend the bounding box of a source to give enough room for the stroke/shadow.

In the short term, there is a workaround:
1. In the filters for the source you want to add a stroke/glow/shadow to, add a `Crop/Pad` filter.  Make sure the filter is added *before* the stroke, glow, or shadow.
2. For the values in `Crop/Pad` make sure `Relative` is checked, and add a negative padding for all four directions.  Something like `-50`.  Adjust this value to show the entire stroke/glow/shadow.

**Comment by LividJava** [comment]
i completely forgot hierarchy applied to filter layers as that was the first thin i tried lol. Thanks!

**Comment by FiniteSingularity** [comment]
Closing as this looks resolved.  Please feel free to re-open if not.
